name: Integration
on: 
  push:
    tags-ignore: [ "*.*.*" ]
    branches: "*"
jobs:
  validate:
    name: "Build, run linter and test project"
    runs-on: ubuntu-latest
    container:
      image: docker://fabernovel/android:api-29-v1.3.0
    env:
      JAVA_TOOL_OPTIONS: "-XX:MinRAMPercentage=20.0 -XX:MaxRAMPercentage=90.0"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process"
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Install Kotlin
        uses: ./.github/actions/setup_kotlin
        with:
          version: 1.7.21
      - name: Validate project
        run: kotlinc -script ./scripts/integrate.main.kts