name: Release
on:
  push:
    tags: [ "*.*.*" ]
jobs:
  release:
    name: "Release the plugin"
    runs-on: ubuntu-latest
    container:
      image: docker://openjdk:8
    env:
      JAVA_TOOL_OPTIONS: "-XX:MinRAMPercentage=20.0 -XX:MaxRAMPercentage=90.0"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process"
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Gradle cache
        uses: actions/cache@v2.1.1
        with:
          path: /root/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Install Kotlin
        uses: ./.github/actions/setup_kotlin
        with:
          version: 1.4.30
      - name: Extract changelog part
        id: set_body
        run: |
          kotlinc -script ./scripts/release.main.kts -- --action=extract-changelog >> /tmp/body
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: /tmp/body
          draft: false
          prerelease: false
      - name: Release to Gradle Plugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: kotlinc -script ./scripts/release.main.kts -- --action=publish