name: Latest Android Gradle Plugin tests
on:
  schedule:
    - cron: "0 20 * * 1"
jobs:
  validate:
    name: "Build, run linter and test project with latest AGP version"
    runs-on: ubuntu-latest
    outputs:
      android_plugin_version: ${{ steps.agp_version.outputs.version }}
    container:
      image: docker://fabernovel/android:api-29-v1.3.0
    env:
      JAVA_TOOL_OPTIONS: "-XX:MinRAMPercentage=20.0 -XX:MaxRAMPercentage=90.0"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process"
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Install Kotlin
        uses: ./.github/actions/setup_kotlin
        with:
          version: 1.6.21
      - name: Validate project
        run: kotlinc -script ./scripts/integrate.main.kts -- --android-plugin-version="+"